name: Run Bot 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install --ignore-scripts=false

      - name: Run Bot
        run: node bot.js
        timeout-minutes: 350
        
